#Application Info
spring.application.name=My-Chat-App-backend

# Local PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/my_chat_app
spring.datasource.username=ahmed
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#Logging (shows SQL + parameters)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Server
server.port= 8080

#Error Handling (makes debugging easier)
server.error.include-message=always
server.error.include-binding-errors=always

#Security
jwt.secret=8015edf96b77266c7b0be5658c02cca8bf1acd0be047403bff8e5f0702624460